---

# VMware Credentials
vcenter_ip:            10.10.1.10
vcenter_username:      username

# VMware Vcenter
#esxi_hostname:          host.example.com
vcenter_cluster:        cluster-00
vcenter_password:       "{{ vault_vcenter_password }}"
#vcenter_template:       DevOps_Ubuntu_16.04_Infra_Template_v1.0 - itemtv0002
vcenter_template:       Ubuntu_16.04
vcenter_datacenter:     DC0
vcenter_resource_pool:  DevOps
vm_folder:              /DC0/vm/cluster-00/DevOps

# Disk Specification
vm_disk:
  - size_gb:    100
    datastore:  ProdOps
    type:       thin

# Hardware Specification
vm_hardware:
  memory_mb:    8192
  num_cpus:     2

# Network Specification
vm_networks:
  - name:       Lab-Pool
