---
# Create VMWare ESX virtual machines
#

- hosts: coreinfra-crud
  vars:
    vcenter_ip:         10.117.28.10
    vcenter_username:   ronald.compos
    vcenter_password:   "{{ vcenter_pw }}"
    vcenter_datacenter: DEN
    vm_folder:          /DEN/vm/01:SF-ProdOps/DevOps/Infra
    vm_name_base:       do-seven-
    start:     1
    end:       1
  connection: local

  tasks:

  - name: Get vm facts 
    vmware_guest_facts:
      hostname:   "{{ vcenter_ip }}"
      username:   "{{ vcenter_username }}"
      password:   "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      folder:     "{{ vm_folder }}"
      name:       "{{ vm_name_base }}{{ item }}"
      validate_certs: no
    delegate_to: localhost
    with_sequence: "{{ start }}-{{ end }}"
    register: vmfacts

  - debug: var=vmfacts

...
