---
# Create VMWare ESX virtual machines
#

- hosts: localhost
  vars:
    vcenter_ip:          10.117.28.10
    vcenter_username:    ronald.compos
    vcenter_password:    welcome1
    vcenter_template:    DevOps_Ubuntu_16.04_Infra_Template_v1.0 - itemv0002
    vcenter_datacenter:  DEN
    vm_name:             do-nitro-1
    vm_folder:           /DEN/vm/01:SF-ProdOps/DevOps/Infra
  connection:            local

  tasks:

  - name: Get template facts 
    vmware_vm_facts:
      hostname:        "{{ vcenter_ip }}"
      username:        "{{ vcenter_username }}"
      password:        "{{ vcenter_password }}"
      #folder:          "{{ vm_folder }}"
      #datacenter:      "{{ vcenter_datacenter }}"
      validate_certs:  no
      vm_type:         template
    delegate_to:       localhost
    register:          vmfacts

  - debug: var=vmfacts

...
